use_default_settings: true

general:
  debug: false
  instance_name: RACO MAS Local Search

search:
  safe_search: 0
  autocomplete: ""
  formats:
    - html
    - json

server:
  bind_address: "0.0.0.0"
  port: 8080
  secret_key: "raco-mas-local-only-change-me"
  limiter: false
  image_proxy: false

ui:
  static_use_hash: true
